// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200703.9

void* winrt_make_SimpleMathComponent_SimpleMath()
{
    return winrt::detach_abi(winrt::make<winrt::SimpleMathComponent::factory_implementation::SimpleMath>());
}
WINRT_EXPORT namespace winrt::SimpleMathComponent
{
    SimpleMath::SimpleMath() :
        SimpleMath(make<SimpleMathComponent::implementation::SimpleMath>())
    {
    }
}
