// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200703.9

#ifndef WINRT_SimpleMathComponent_2_H
#define WINRT_SimpleMathComponent_2_H
#include "winrt/impl/SimpleMathComponent.1.h"
WINRT_EXPORT namespace winrt::SimpleMathComponent
{
    struct __declspec(empty_bases) SimpleMath : SimpleMathComponent::ISimpleMath
    {
        SimpleMath(std::nullptr_t) noexcept {}
        SimpleMath(void* ptr, take_ownership_from_abi_t) noexcept : SimpleMathComponent::ISimpleMath(ptr, take_ownership_from_abi) {}
        SimpleMath();
    };
}
#endif
