// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200703.9

#ifndef WINRT_SimpleMathComponent_1_H
#define WINRT_SimpleMathComponent_1_H
#include "winrt/impl/SimpleMathComponent.0.h"
WINRT_EXPORT namespace winrt::SimpleMathComponent
{
    struct __declspec(empty_bases) ISimpleMath :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISimpleMath>
    {
        ISimpleMath(std::nullptr_t = nullptr) noexcept {}
        ISimpleMath(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
